### ISSUE TITLE
能否给个release版

### ISSUE THREAD

**Issue by lersh** [xjbeta/Aria2D#1]
编译提示找不到jsonswift

**Comment by xjbeta** [comment]
直接command＋R运行试试，第一次的话确实是会报这个错。

Selphy notifications@github.com于2016年4月16日周六 下午10:59写道：

**Comment by HatCloud** [comment]
不行，还是一直报这个错误。
我不是很懂 Mac 开发，不过我按照开发 Android 的经验，清理了一下 project，但也没起作用

**Comment by xjbeta** [comment]
[Aria2D.app.zip](https://github.com/xjbeta/Aria2D/files/222946/Aria2D.app.zip)

**Comment by HatCloud** [comment]
谢谢
