### ISSUE TITLE
safari extension

### ISSUE THREAD

**Issue by tao-bioinfo** [xjbeta/Aria2D#12]
Since there's no any proper safari extension for download accretion up to now, do you have any plan to develop a safari extension?

**Comment by xjbeta** [comment]
NO, I didn't pay for the Apple Developer Program.

**Comment by mangonerd** [comment]
I don’t know if it will be feasible for you, but apparently you can package the safari extension inside the app itself? [Safari app extensions](https://developer.apple.com/documentation/safariservices/safari_app_extensions)
Some other projects that might help with your development:

- https://github.com/miniers/safari2aria/
- https://github.com/baptistecdr/aria2-extensions

Requesting once again for a safari extension to replace the default downloader with **aria2d** :)
