### ISSUE TITLE
home-brew cask download error

### ISSUE THREAD

**Issue by cysnb** [xjbeta/Aria2D#15]
Hi, there are an error when `brew cask install aria2d` :

`
[~/Downloads]$ brew cask install aria2d
Updating Homebrew...
==> Downloading https://raw.githubusercontent.com/xjbeta/AppUpdaterAppcasts/master/Aria2D/Aria2D%201.3.5.dmg
##O#- #
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to raw.githubusercontent.com:443
Error: Download failed on Cask 'aria2d' with message: Download failed: https://raw.githubusercontent.com/xjbeta/AppUpdaterAppcasts/master/Aria2D/Aria2D%201.3.5.dmg
`

Is the download url error? The url should be `https://github.com/xjbeta/Aria2D/releases/download/1.3.5(501)/Aria2D.1.3.5.dmg` ???

**Comment by xjbeta** [comment]
No problem with the link. Check your network.
